version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: my_php_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"

  php:
    image: php:7.4
    container_name: php_container
    volumes:
      - ./app:/var/www/html
    depends_on:
      - rabbitmq

# networks:
#   default:
#     external:
#       name: my_network
  
    
